//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaniKarijera.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DKEntities : DbContext
    {
        public DKEntities()
            : base("name=DKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dizajn> dizajn { get; set; }
        public virtual DbSet<prostorije> prostorije { get; set; }
        public virtual DbSet<raspored> raspored { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<virtualne_vizitke> virtualne_vizitke { get; set; }
        public virtual DbSet<korisnici> korisnici { get; set; }
        public virtual DbSet<poslodavci> poslodavci { get; set; }
        public virtual DbSet<radnici> radnici { get; set; }
        public virtual DbSet<glasanje> glasanje { get; set; }
    }
}
