//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaniKarijera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class poslodavci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public poslodavci()
        {
            this.raspored = new HashSet<raspored>();
            this.virtualne_vizitke = new HashSet<virtualne_vizitke>();
            this.radnici = new HashSet<radnici>();
            this.glasanje = new HashSet<glasanje>();
        }
    
        public int id_poslodavca { get; set; }
        public string naziv { get; set; }
        public string link { get; set; }
        public string web { get; set; }
        public string opis { get; set; }
        public string slika { get; set; }
        public string logo { get; set; }
        public Nullable<bool> glasanje1 { get; set; }
        public bool popis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<raspored> raspored { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<virtualne_vizitke> virtualne_vizitke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<radnici> radnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<glasanje> glasanje { get; set; }
    }
}
