//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaniKarijera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prostorije
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prostorije()
        {
            this.raspored = new HashSet<raspored>();
        }
    
        public int id_prostorije { get; set; }
        public string naziv { get; set; }
        public string lokacija { get; set; }
        public string boja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<raspored> raspored { get; set; }
    }
}
