//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaniKarijera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class raspored
    {
        public int id_raspored { get; set; }
        public Nullable<int> id_poslodavca { get; set; }
        public string naziv_predavanja { get; set; }
        public string slika { get; set; }
        public int id_prostorije { get; set; }
        public System.DateTime datum { get; set; }
        public System.TimeSpan od { get; set; }
        public System.TimeSpan @do { get; set; }
    
        public virtual prostorije prostorije { get; set; }
        public virtual poslodavci poslodavci { get; set; }
    }
}
